//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEventFunEntities : DbContext
    {
        public dbEventFunEntities()
            : base("name=dbEventFunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<t一般會員> t一般會員 { get; set; }
        public virtual DbSet<t主題聊天室> t主題聊天室 { get; set; }
        public virtual DbSet<t主題類型> t主題類型 { get; set; }
        public virtual DbSet<t企業會員> t企業會員 { get; set; }
        public virtual DbSet<t地區> t地區 { get; set; }
        public virtual DbSet<t次主題類型> t次主題類型 { get; set; }
        public virtual DbSet<t行事曆> t行事曆 { get; set; }
        public virtual DbSet<t行事曆明細> t行事曆明細 { get; set; }
        public virtual DbSet<t城市> t城市 { get; set; }
        public virtual DbSet<t活動> t活動 { get; set; }
        public virtual DbSet<t活動日期> t活動日期 { get; set; }
        public virtual DbSet<t活動票券> t活動票券 { get; set; }
        public virtual DbSet<t活動場次> t活動場次 { get; set; }
        public virtual DbSet<t活動圖片> t活動圖片 { get; set; }
        public virtual DbSet<t商品> t商品 { get; set; }
        public virtual DbSet<t商品訂單> t商品訂單 { get; set; }
        public virtual DbSet<t商品訂單明細> t商品訂單明細 { get; set; }
        public virtual DbSet<t商品訂單狀態> t商品訂單狀態 { get; set; }
        public virtual DbSet<t商品圖片> t商品圖片 { get; set; }
        public virtual DbSet<t票券訂單> t票券訂單 { get; set; }
        public virtual DbSet<t票券訂單明細> t票券訂單明細 { get; set; }
        public virtual DbSet<t票券購物車> t票券購物車 { get; set; }
        public virtual DbSet<t聊天室> t聊天室 { get; set; }
        public virtual DbSet<t評鑑> t評鑑 { get; set; }
        public virtual DbSet<t會員喜愛次主題> t會員喜愛次主題 { get; set; }
        public virtual DbSet<t會員喜愛活動> t會員喜愛活動 { get; set; }
        public virtual DbSet<t會員最愛行事曆> t會員最愛行事曆 { get; set; }
        public virtual DbSet<t管理者資料表> t管理者資料表 { get; set; }
        public virtual DbSet<t廣告> t廣告 { get; set; }
        public virtual DbSet<t論壇文章留言> t論壇文章留言 { get; set; }
        public virtual DbSet<t論壇文章資料表> t論壇文章資料表 { get; set; }
    }
}
