//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class t一般會員
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t一般會員()
        {
            this.t行事曆 = new HashSet<t行事曆>();
            this.t票券訂單 = new HashSet<t票券訂單>();
            this.t票券購物車 = new HashSet<t票券購物車>();
            this.t評鑑 = new HashSet<t評鑑>();
            this.t會員喜愛次主題 = new HashSet<t會員喜愛次主題>();
            this.t會員喜愛活動 = new HashSet<t會員喜愛活動>();
        }
    
        public string f會員編號 { get; set; }
        public string f會員帳號 { get; set; }
        public string f會員密碼 { get; set; }
        public string f會員信箱 { get; set; }
        public string f會員名稱 { get; set; }
        public Nullable<bool> f會員性別 { get; set; }
        public Nullable<System.DateTime> f出生年月日 { get; set; }
        public string f會員簡介 { get; set; }
        public string f會員行動電話 { get; set; }
        public string f城市編號 { get; set; }
        public string f郵遞區號 { get; set; }
        public string f地址 { get; set; }
        public string f會員照片 { get; set; }
        public Nullable<bool> f帳號狀態 { get; set; }
        public Nullable<System.DateTime> f上次登入時間 { get; set; }
        public Nullable<System.DateTime> f創建時間 { get; set; }
        public HttpPostedFileBase photo { get; set; }

        public virtual t地區 t地區 { get; set; }
        public virtual t城市 t城市 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t行事曆> t行事曆 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t票券訂單> t票券訂單 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t票券購物車> t票券購物車 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t評鑑> t評鑑 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t會員喜愛次主題> t會員喜愛次主題 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t會員喜愛活動> t會員喜愛活動 { get; set; }
    }
}
