//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t主題聊天室
    {
        public int f聊天訊息編號 { get; set; }
        public string f主題類型編號 { get; set; }
        public string f會員編號 { get; set; }
        public string f內容 { get; set; }
        public Nullable<System.DateTime> f時間 { get; set; }
    }
}
