//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class t企業會員
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t企業會員()
        {
            this.t活動 = new HashSet<t活動>();
            this.t廣告 = new HashSet<t廣告>();
        }
        public HttpPostedFileBase photo { get; set; }
        public string f企業編號 { get; set; }
        public string f統一編號 { get; set; }
        public string f企業帳號 { get; set; }
        public string f企業密碼 { get; set; }
        public string f企業名稱 { get; set; }
        public string f企業簡介 { get; set; }
        public string f企業電話 { get; set; }
        public string f城市編號 { get; set; }
        public string f郵遞區號 { get; set; }
        public string f企業地址 { get; set; }
        public string f聯絡人 { get; set; }
        public string f聯絡人行動電話 { get; set; }
        public string f企業照片 { get; set; }
        public string f企業信箱 { get; set; }
        public Nullable<System.DateTime> f企業創建日期 { get; set; }
        public Nullable<bool> f企業帳號狀態 { get; set; }
    
        public virtual t地區 t地區 { get; set; }
        public virtual t城市 t城市 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t活動> t活動 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t廣告> t廣告 { get; set; }
    }
}
