//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t商品訂單
    {
        public string f商品訂單編號 { get; set; }
        public string f會員編號 { get; set; }
        public Nullable<System.DateTime> f商品訂單日期 { get; set; }
        public Nullable<System.DateTime> f商品到貨日期 { get; set; }
        public string f收貨人 { get; set; }
        public string f收貨地址 { get; set; }
        public Nullable<int> f商品訂單狀態編號 { get; set; }
        public Nullable<System.DateTime> f完成時間 { get; set; }
    }
}
