//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t商品
    {
        public string f商品編號 { get; set; }
        public string f活動編號 { get; set; }
        public string f商品名稱 { get; set; }
        public string f商品描述 { get; set; }
        public Nullable<System.DateTime> f上架時間 { get; set; }
        public Nullable<decimal> f販賣價格 { get; set; }
        public Nullable<int> f庫存 { get; set; }
        public Nullable<int> f已售數量 { get; set; }
        public Nullable<bool> f上架狀態 { get; set; }
    }
}
