//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class t廣告
    {
        public int f廣告編號 { get; set; }
        public string f企業編號 { get; set; }
        public string f廣告名稱 { get; set; }
        public string f廣告內容 { get; set; }
        public Nullable<System.DateTime> f起始日期 { get; set; }
        public Nullable<System.DateTime> f結束日期 { get; set; }
        public Nullable<int> f瀏覽次數 { get; set; }
        public string f廣告圖片 { get; set; }
        public string f廣告網址 { get; set; }
        public Nullable<bool> f廣告上下架 { get; set; }
        public HttpPostedFileBase photo { get; set; }
        public virtual t企業會員 t企業會員 { get; set; }
    }
}
