//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class t活動圖片
    {
        public int f圖片編號 { get; set; }
        public string f活動編號 { get; set; }
        public string f活動圖片 { get; set; }
        public HttpPostedFileBase photo { get; set; }
        public virtual t活動 t活動 { get; set; }
    }
}
