//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t活動票券
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t活動票券()
        {
            this.t票券訂單明細 = new HashSet<t票券訂單明細>();
            this.t票券購物車 = new HashSet<t票券購物車>();
        }
    
        public string f票券編號 { get; set; }
        public string f場次編號 { get; set; }
        public string f票券名稱 { get; set; }
        public Nullable<decimal> f票券金額 { get; set; }
        public Nullable<int> f票券庫存 { get; set; }
        public Nullable<int> f票券已售數量 { get; set; }
    
        public virtual t活動場次 t活動場次 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t票券訂單明細> t票券訂單明細 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t票券購物車> t票券購物車 { get; set; }
    }
}
