//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t活動
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t活動()
        {
            this.t活動日期 = new HashSet<t活動日期>();
            this.t活動圖片 = new HashSet<t活動圖片>();
            this.t評鑑 = new HashSet<t評鑑>();
            this.t會員喜愛活動 = new HashSet<t會員喜愛活動>();
        }
    
        public string f活動編號 { get; set; }
        public string f次主題編號 { get; set; }
        public string f企業編號 { get; set; }
        public string f活動聯絡人 { get; set; }
        public string f聯絡人電話 { get; set; }
        public string f聯絡人信箱 { get; set; }
        public string f活動名稱 { get; set; }
        public string f活動網址 { get; set; }
        public string f活動簡介 { get; set; }
        public string f活動內容 { get; set; }
        public Nullable<int> f人氣 { get; set; }
    
        public virtual t企業會員 t企業會員 { get; set; }
        public virtual t次主題類型 t次主題類型 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t活動日期> t活動日期 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t活動圖片> t活動圖片 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t評鑑> t評鑑 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t會員喜愛活動> t會員喜愛活動 { get; set; }
    }
}
