//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t票券購物車
    {
        public string f票券編號 { get; set; }
        public string f會員編號 { get; set; }
        public int 票券數量 { get; set; }
    
        public virtual t一般會員 t一般會員 { get; set; }
        public virtual t活動票券 t活動票券 { get; set; }
    }
}
