//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class t管理者資料表
    {
        public int f管理者編號 { get; set; }
        public string f管理者帳號 { get; set; }
        public string f管理者密碼 { get; set; }
        public string f管理者名稱 { get; set; }
        public string f管理者電話 { get; set; }
        public string f個人照片 { get; set; }
        public Nullable<bool> f帳號狀態 { get; set; }
        public Nullable<System.DateTime> f上次登入時間 { get; set; }
        public string f管理者信箱 { get; set; }
        public string f簡介 { get; set; }
        public string f地址 { get; set; }
        public Nullable<System.DateTime> f創建時間 { get; set; }
        public HttpPostedFileBase photo { get; set; }
    }
}
