//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t聊天室
    {
        public int f聊天室編號 { get; set; }
        public string f一般會員編號 { get; set; }
        public string f企業會員編號 { get; set; }
        public string f發話方編號 { get; set; }
        public string f聊天內容 { get; set; }
    }
}
