//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t行事曆明細
    {
        public int f行事曆明細編號 { get; set; }
        public string f行事曆編號 { get; set; }
        public string f場次編號 { get; set; }
    
        public virtual t行事曆 t行事曆 { get; set; }
    }
}
