//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t論壇文章資料表
    {
        public string f文章編號 { get; set; }
        public string f主題編號 { get; set; }
        public string f文章標題 { get; set; }
        public string f文章內容 { get; set; }
        public Nullable<System.DateTime> f發布時間 { get; set; }
        public string f會員編號 { get; set; }
        public Nullable<int> f文章瀏覽數 { get; set; }
        public Nullable<System.DateTime> f最新發布時間 { get; set; }
        public string f最新發表會員編號 { get; set; }
        public string 最新發表會員 { get; set; }
        public string 主題名稱 { get; internal set; }
        public string 會員名稱 { get; internal set; }
        public int 樓層數 { get; internal set; }
        public string 會員帳號 { get; internal set; }
        public string 現在樓層 { get; internal set; }
        public string 會員頭像 { get; internal set; }
    }
}
