//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFunWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class t論壇文章留言
    {
        public string f文章編號 { get; set; }
        public int f留言編號 { get; set; }
        public string f留言內容 { get; set; }
        public string f會員編號 { get; set; }
        public Nullable<System.DateTime> f發布時間 { get; set; }
    }
}
